### ISSUE TITLE
第一周作业

### ISSUE THREAD

**Issue by yanyonghua** [AlgorithmCHUNZHAO/AlgorithmCHUNZHAO#4]
#学号:G20210541020043
#班级:算法春招班
#作业链接:https://github.com/yanyonghua/AlgorithmCHUNZHAO.git

**Comment by yanyonghua** [comment]
....

**Comment by HiFengGe** [comment]
#学号:G20210541020032
#班级:算法春招班
#作业链接:https://github.com/HiFengGe/AlgorithmCHUNZHAO/tree/main/Week_04
